WIP - npm package for enclave API
provable-things/ptokens.js-v1 pull request #1
Opened 2019-10-29 10:25 UTC by allemanfredi

As described in the title, this PR shows the progresses about the npm package for enclave API.

2019-10-29 13:43 UTC, gskapka requested changes
Super neat with the option of users either using promises or callbacks. Though tbh I should imagine most people will be using the promises because callbacks are just urgh.

Here are various things to look into/change:

 - Looking at something like `/packages/ptokens-enclave/src/index.js` You can [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) it out a TON: 

```javascript
const makeApiCall = (_apiPath, _callback) => // This could even go in utils
  new Promise((resolve, reject) =>
    api.get(_apiPath)
      .then(res => callback ? callback(res, null) : resolve(res))
      .catch(err => cb ? callback(null, err) : reject(err)
    )

class Enclave {
  /**
   * @param {Function=} null - cb
   */
  ping(_callback = null) {
    return makeApiCall('/ping', _callback)
  }
  /**
   * @param {Integer} limit
   * @param {Function=} null - cb
   */
  getEthReport(limit, _callback = null) {
    return makeApiCall(`/eth-reports/limit/${limit}`, _callback)
  }
  /**
   * @param {Integer} limit
   * @param {Function=} null - cb
   */
  getEosReport (limit, _callback = null) {
    return makeApiCall(`/eos-reports/limit/${limit}`, _callback)
  }
  // etc...
}
```

- Please can you clean-up the commit history a bit w/ rebasing in order to remove multiple examples of "update README", "rm line" etc.

- After `pnpm i`, `npm run test` results in errors for me relating to jest. Please update the `readme`'s instructions for running tests successfully.

- Running `npx eslint ./` gives a log of errors. Please fix!

- Please no single letter variable names!!

I've also left some comments in the code itself. 

Finally, can you please briefly explain what lerna, jest and rollup are each doing here? Thanks!

2019-10-29 13:43 UTC, gskapka commented on packages/ptokens-enclave/src/index.js
> +  ping (cb = null) {
Does this pass the linter? Because if so it shouldn't, I'm pretty sure there should not be a space between the function name and the parentheses...

```suggestion
  ping(cb = null) {
```

Same goes everywhere else too.

2019-10-29 13:43 UTC, gskapka commented on packages/ptokens/tests/ptokens.test.js
> +    ethProvider: 'https://kovan.infura.io/v3/4762c881ac0c4938be76386339358ed6',
Is this your INFURA token? If so you'll need to create yourself a new one and abandon this.

You'll need to either make the test require an infura token from the user, or use `https://rpc.slock.it/kovan`. The latter is easier but less ideal since what happens if that node goes down (as it has in the past!)?.

2019-10-29 13:43 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +        }, 3000)
Please can we make constants of these, instead of just magic numbers.

2019-10-29 13:43 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +        if (this.isWeb3Injected)
If using `if` and `else` we should use braces. But situations like here we don't need braces because each block has only a single statement, which means we can use a simple ternary instead. Plus we can lose the horrible declaration with `null`:

```javascript
const account = this.isWeb3Injected
  ? await _getEthAccount(this.web3)
  : this.web3.defaultAccount
```

Same elsewhere too.

2019-10-29 13:43 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +  getCirculatingSupply (cb = null) {
This and the function above it look like a good candidate for DRYing out.

2019-10-29 15:58 UTC, allemanfredi commented
Thank you for your suggestions, i really appreciated them! Regarding lerna, jest and rollup i try do an explanation.
Lerna is simply a tool that allows you to handle more packages within a project. In our case, we have ptokens.js that is the project and inside it we have more packages (`ptokens`, `ptokens-peos`, `ptokens-enclave` ...)
Rollup is a module bundler (as webpack) that (i read) is better than webpack for creating libraries. What rollup does here is simply creating bundles of each package in different format (UMD, ESM, CJS) since the library can be used within a browser as well as in a normal backend.
The main rollup config file (`rollup.config.js`) is kept in the root of the folder and each package creates an ad-hoc version for it in this way:

(ex: for `ptokens-peos` package)
```js
import pkg from './package.json'
import rollupConfig from '../../rollup.config'

export default rollupConfig('pEOS', pkg.name)
```

In this way we have only one config file that is totally configurable by each package.

With `npm run build`, rollup will create a `dist` folder within each package in which you can find the bundles.

Same thing for Jest, the main config file and is kept in the root folder and each package create the one by calling it from their folder.

```js
const jestConfig = require('../../jest.config')

module.exports = jestConfig()
```

2019-10-30 10:01 UTC, gskapka commented
Before I add a second review @allemanfredi, I _still_ can't run the tests at all.

I clone the repo, then `pnpm i` then `npm run test` per the `README` and all I get is: 

```
>=> npm run test

> ptokens@ test /home/user/ptokens.js
> lerna run test

lerna notice cli v3.18.3
lerna info Executing command in 3 packages: "npm run test"
lerna ERR! npm run test exited 1 in 'ptokens-enclave'
lerna ERR! npm run test stdout:

> ptokens-enclave@0.0.1 test /home/user/ptokens.js/packages/ptokens-enclave
> jest


lerna ERR! npm run test stderr:
sh: 1: jest: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ptokens-enclave@0.0.1 test: `jest`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ptokens-enclave@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-10-30T09_59_31_137Z-debug.log

lerna ERR! npm run test exited 1 in 'ptokens-enclave'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ptokens@ test: `lerna run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ptokens@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-10-30T09_59_31_171Z-debug.log

```

So please can you look into the above and then elaborate in the `README` about how to run the tests successfully?

2019-10-30 13:16 UTC, gskapka requested changes
Had a closer look at the tests this time and they're looking great, nice and thorough! Some changes as ever (again, intended to get this as polished as possible!):

- DRY out the `ptokens-enclave/src/utils/index.js` further via:

```javascript
// in the utils:

const makeApiCall(_callType, _apiPath, _callback)
  new Promise((resolve, reject) =>
    api[_callType](_apiPath)
      .then(_res => _callback ? _callback(_res, null) : resolve(_res))
      .catch(_err => _callback ? _callback(null, _err) : reject(_err))
  )

// in the class in index:

ping(_callback = null) {
  return makeApiCall('GET', 'ping', _callback)
}
```

- lets flatten out the dir structure in `ptokens-enclave` by dropping the `utils` dir and just dropping the util fxns directly into the `index.js`. Unless a UTIL fxn is being used _in more than one file_ there's no point abstracting it out to it's own file. Here there is no re-use so lets simplify the whole directory.

- Non-code related, but can this:

```javascript
/**
 * 
 * @param blah blah blah
 */
```

become:

```javascript
/**
 * @param blah blah blah
 */
```
The extra `*` really bothers me aesthetically. Plus also can we lose the blank lines above `/**` since we already have a ton of space thanks to the `/** */` comments and so don't need another blank line.

 - can the `packages` dir get renamed to `ptoken-packages`? 

- Can the sub-readme's get their own instructions for running that packages' tests please.

- Can the sub-readme's get more elaborate instructions for usage too? E.G. The enclave `README` just shows how to instantiate an enclave. How can a user make a _call_ to the enclave now that they've instantiated it?

-  Even after your instructions re running the tests, when I try and run the tests in the enclave dir, I get the same jest errors. Presume you have that globally install also? Make sure to include the package so the user doesn't need global installs!

```
user@temp-connector:~/ptokens.js/packages/ptokens-enclave|dev-alessandro⚡
>=> npm run test

> ptokens-enclave@0.0.1 test /home/user/ptokens.js/packages/ptokens-enclave
> jest

sh: 1: jest: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ptokens-enclave@0.0.1 test: `jest`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ptokens-enclave@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-10-30T13_05_52_034Z-debug.log
```

 - More instructions for use in the `ptokens-peos/README.md` please. Eg, how can a user deposit EOS to get pEOS? And do another for the opposite. 

I'll stop here for now. There are more comments inline in the code as well. Make any changes/fixes and re-request review where I'll go on to the `ptokens-peos` stuff more thoroughly.

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/src/utils/index.js
> +const api = axios.create({
This is an actual CONSTANT right? And so can we give it `SCREAMING_SNAKE_CASE` please?

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/src/utils/index.js
> + *
These are the extra asterisks I'm disliking.

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/src/utils/index.js
> +
These are the extra line breaks I'm disliking.

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/tests/ptokens-enclave.test.js
> +  const expectedResult = 'Provable pong!'
There are various constants in here that might as well be defined at the top of the file as actual `SCREAMING_SNAKE_CASE` constants, since they're used multiple times.

```javascript
const PING_RETURN_VALUE = 'Provable pong!'
const EOS_SUBMISSION_RETURN_VALUE = 'Eos block submitted to the enclave!'
// etc
```

Now, if we change any of these return values from the enclave API you can update your tests in online instead of having to hunt down several places where you've tested against the return value.

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/tests/ptokens-enclave.test.js
> +  const hash = '3aa61c0188e065a7a90234dc3d544e8791f76423b5eb34d63201531c61f24066'
Repeated. Factor out as constant.

2019-10-30 13:16 UTC, gskapka commented on packages/ptokens-enclave/tests/utils.js
> +const ethBlock = {
`SCREAMING_SNAKE_CASE` for all constants please. By which I mean _actual_ constants, not just things declared with `const`.

Same goes throughout library.

2019-10-31 09:33 UTC, allemanfredi commented
Thank you for your suggestion! i added jest in each package but it is not totally correct. Since we are using lerna, this kind of packages (jest, eslint and so on) should be only in the root directory and instead of testing the package individually you should do all the tests from the root (where there is jest). Regarding the asterisk i'm sorry, i toke the Visual Studio suggestions for comments.

2019-11-17 19:18 UTC, gskapka requested changes
Left some more inline comments here and there. Going through the meatier functions this time and trying to get things ship-shape for publishing.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +        gasLimit: 10000000,
Magic number, should either make a constant or parameterize it. Also, is this not too hight for mainnet and will cause an error where it exceeds block gas limit? I know it increased recently but I can't remember what too. I know this will be too high for test nets though. So lets use a more reasonable figure.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +        value: '0x00',
Is this hardcoded to zero because these txs are expected to only be minting/burning txs?

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +    contract.methods[_method]().call()
What if I pass in a `method` here that can't be `call()`ed? 

What `method`s are we expecting this fxn to be used for?

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +const _getTotalOf = (_web3, _method, _isWeb3Injected) =>
`getTotalOf` what? Make more descriptive please!

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +      const gasPrice = await _web3.eth.getGasPrice()
Probably better to make this more flexible by parameterizing this and making the call to `getGasPrice()` futher up the call chain.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +  return accounts[0]
Do we ever need to get `account[>0]`?

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/utils/eos.js
> +const _isValidEosAccount = _account => {
```suggestion
const _isValidEosAccountName = _accountName => {
```

Plus in fxn body too ofc.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/contract/pEOSToken.json
> +[
The directory is called `contract` but there's no contract in it, just a contract ABI. Will there ever be a contract in it? If not, rename to `contractAbi` please.

Same goes for the file itself. More descriptive please. `pEOSTokenETHContractAbi.json`

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +    if (_amount < MININUM_NUMBER_OF_PEOS_MINTED)
```suggestion
    if (_amount < MINIMUM_MINTABLE_PEOS_AMOUNT)
```

...and everywhere else ofc.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +              quantity: accurateAmount + ' EOS',
Should make a separate function for this so it's unit-testable, so this line would become: 

```suggestion
              quantity: getAmountInEOSFormat(_amount),
```

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +          expireSeconds: 30
Let's make this the max 60s. Also, these are both magic numbers. Please fix.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +          if (res.broadcast === false && !isSeen) {
Why are we using `!` for one and not the other?

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +          res = await this.enclave.getIncomingTransactionStatus(polledTx)
The multiple over-writings of `res` here are confusing and ugly. 

Lets make things easier by naming each version properly to something more useful than `res` please.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +          }
Please re-order to make less byzantine. Flip the first conditional and it'll be much clearer for future readers. Also by now you should have renamed this `res` to something much clearer, which will help too.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +        const accurateAmount = _amount.toFixed(4)
4 is a magic number. Please fix.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +        const accurateAmount = _amount * Math.pow(10, TOKEN_DECIMALS)
Factor out as util so it's unit-testable. That way also the function name can help explain what's going on here.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +    return _getTotalOf(
I asked else where what the `_getTotalOf` function was getting the totals of. These explain that somewhat but also highlight that bad function naming.

Since the function is actually just making a contract `.call()`, rename it to reflect that. Then these functions are all well named, and are justing using the abstracted `.call()` function nicely.

2019-11-17 19:18 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +import polling from 'light-async-polling'
Was actually about to rant about how things like this are one of the banes of the `npm` way of doing things (see for example the `isOdd` and `isEven` packages), because relying on external packages for such simple functions seems insane to me when the underlying package owner could just change them at their whim.

Then I noticed that the package is by you. So I won't be too harsh. 

But still, I stand by my issue of package usage for such tiny functions. It's better to have something like this as a `util` in here rather than adding into the dependency burden. That said, it's `npm` so we by default have a large and painful dependency issue.

So yeah, I'll let this one pass for now.

2019-11-17 19:44 UTC, allemanfredi commented on packages/ptokens-peos/src/utils/eth.js
> +        value: '0x00',
yes!

2019-11-17 19:45 UTC, allemanfredi commented on packages/ptokens-peos/src/contract/pEOSToken.json
> +[
ok!

2019-11-17 19:49 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +          if (res.broadcast === false && !isSeen) {
because `res.broadcast` can be also null so if i use `!` this condition will be verified even if when the enclave has not received the tx

2019-11-17 19:50 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +          res = await this.enclave.getIncomingTransactionStatus(polledTx)
ok!

2019-11-17 19:50 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +          }
I think that the response from the enclave api can be null if the enclave has not received the tx yet. maybe the response is changed but i used this condition because the response could be null.

2019-11-17 19:52 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +import polling from 'light-async-polling'
ok greg sorry for the mistake! maybe should i copy the code here?

2019-11-17 19:52 UTC, gskapka commented on packages/ptokens-peos/src/utils/eth.js
> +        value: '0x00',
Gotcha! In which case, lets make things more clear by providing a generic transactor to be used internally, followed by two functions that use that generic one: One for the minting transactins and one for the burning one.

2019-11-17 19:55 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +          }
I understand _why_ you're using the condition, don't worry about that. What I'm saying is to flip the bool so your logic becomes easier to read:

`if (!res)...`

Once you've re-written it like that you'll see how much more simple it is for other people to follow your logic. (Even though it's simple in this case, true, but it can always be made clearer and we should always try to make it clearer even in cases like this).

2019-11-17 22:21 UTC, gskapka commented on packages/ptokens-peos/src/index.js
> +import polling from 'light-async-polling'
Hahah don't worry - it's not a mistake! I'm just a fan of not relying on other packages for such tiny functions. However in this case the other person is you!

2019-11-18 14:36 UTC, allemanfredi commented on packages/ptokens-peos/src/utils/eth.js
> +  return accounts[0]
this function is used when user uses the web3 injected version. Unfortunately i read that metamask is changing the in-page script by removing functions and using an event-drive approach because of the new features (plugin). i also read that this feature will be availabe in December so is probably that i will have to chage this code.

2019-11-18 14:48 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +          expireSeconds: 30
done!

2019-11-18 14:50 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +    if (_amount < MININUM_NUMBER_OF_PEOS_MINTED)
done!

2019-11-18 21:03 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +              quantity: accurateAmount + ' EOS',
done!

2019-11-18 21:03 UTC, allemanfredi commented on packages/ptokens-peos/src/utils/eos.js
> +const _isValidEosAccount = _account => {
done!

2019-11-18 21:04 UTC, allemanfredi commented on packages/ptokens-peos/src/utils/eth.js
> +        gasLimit: 10000000,
I decided to get the gas limit in a dynamic way with the following function:

```
const _getEthGasLimit = _web3 =>
  new Promise((resolve, reject) => {
    _web3.eth.getBlock('latest')
      .then(_block => resolve(_block.gasLimit))
      .catch(_err => reject(_err))
  })
```
What do you think about that?

2019-11-18 21:52 UTC, allemanfredi commented
With the addition of `_eosMemo` in the burning function within the smart contract, we should give the possibility to the user (in redeem fx) to set the `_eosMemo` value. Since he might not be interested in setting this value I thought of setting it to a default value.

For this reason, the redeem function would become like this:

```
export const DEFAULT_EOS_MEMO = 'pEOS Redeem'
redeem(_amount, _eosAccountName, _eosMemo = DEFAULT_EOS_MEMO) { ... }
```

2019-11-19 08:14 UTC, allemanfredi commented on packages/ptokens-peos/src/contract/pEOSToken.json
> +[
done!

2019-11-19 08:17 UTC, allemanfredi commented on packages/ptokens-peos/src/index.js
> +        const accurateAmount = _amount.toFixed(4)
done!

2019-11-19 08:17 UTC, allemanfredi commented on packages/ptokens-peos/src/utils/eth.js
> +        value: '0x00',
done only for burning tx since the minting tx is not possible from the pEOS eth smart contract!

2019-11-19 09:41 UTC, gskapka commented
^ Yep, good idea & I totally agree. Allow the option to set but default to that fallback memo.

2019-12-05 15:23 UTC, merged